### ISSUE TITLE
multiple connection

### ISSUE THREAD

**Issue by TrejGun** [saintedlama/mongoose-version#21]
this all works just fine when connection is created like 

``` js
mongoose.connect(config.mongo.url, config.mongo.options, () => {
    console.log("connected :)")
});
```

but silently fails when connection is created like

``` js
mongoose.createConnection(configs.mongo.url, configs.mongo.options, () => {
    console.log("connected :)");
})
```

which is actually correct because `mongoose.connection` is not set

so can you please add some possibility to pass `connection` to where models are registered
https://github.com/saintedlama/mongoose-version/blob/master/lib/strategies/collection.js#L20

**Comment by relvao** [comment]
You can try out https://www.npmjs.com/package/lackey-mongoose-version

It's pretty much still just @saintedlama code. We just added the multiple connection support.

We also decided to remove the array option. Mongo has a fairly low size limit per document. We have already hit it a couple of times and given the fact we don't actually use that we just stripped it out.

We would be more than happy to move back to using this plugin if it supports multiple connections, but for the time being this quick fork solved our problem.

**Comment by saintedlama** [comment]
Do you have a pull request for the multiple connection feature @relvao? Will merge ASAP

**Comment by relvao** [comment]
I had this one https://github.com/saintedlama/mongoose-version/pull/18 
Can you merge it or would I have to do a new pull request?

**Comment by saintedlama** [comment]
I'd need a new pull request since the repository containing the pull request has been deleted

**Comment by relvao** [comment]
@saintedlama  OK. Let me re-build it this weekend and do another pull request. 

The connection should make little difference in the tests. I had replicated all the tests in another folder just to verify/proove if it made no difference, but I guess a basic test checking if the basic features still work with multiple connections should be enough. I don't see any point in duplicating everything. What do you think?

**Comment by saintedlama** [comment]
Duplicating all the tests does not make sense. If the multiple connection feature works in a basic scenario it will (most likely) work in other scenarios as well. Code coverage generated by istanbul is a good measurement for adding new tests.

**Comment by CTAPbIuMABP** [comment]
@relvao have you had a chance to work on this or do you need a help?

**Comment by relvao** [comment]
Not yet, sorry. I'll try and do it soon.
