### ISSUE TITLE
Newest version not published in npm?

### ISSUE THREAD

**Issue by tirithen** [saintedlama/mongoose-version#4]
I added "mongoose-version": "0.2.x" to my package.json but got a version using the clone module instead of the owl-deepcopy module. The mongoose-version module's package.json says 0.2.2 but the code is not the same as in the github repo. Is the latest version published to npm?

**Comment by neeharv** [comment]
Can the latest version of this be published to npm? Or is this not being maintained anymore?

**Comment by saintedlama** [comment]
It's been maintained, what feature do you miss?
